### ISSUE TITLE
install procedure

### ISSUE THREAD

**Issue by jgranduel** [neuecc/RespClient#19]
Hi, 

thanks for this project.
Could you add a way on how to install? The only way you mention is:

    # Standalone PowerShell Cmdlet and .NET Client, requires System.Management.Automation
    PM> Install-Package RespClient

but it could also be done through nuget command line for people, like myself, who don't have VS installed.

    PS4 > nuget install RespClient

I had trouble and had to clean $env:APPDATA\Roaming\NuGet\NuGet.Config, but it went fine.
By default it installs locally.

Would you consider package for Chocolatey?

    PS4 > Get-Command -Module respclient

    CommandType     Name                                               ModuleName
    -----------     ----                                               ----------
    Cmdlet          Begin-RedisPipeline                                RespClient
    Cmdlet          Connect-RedisServer                                RespClient
    Cmdlet          Disconnect-RedisServer                             RespClient
    Cmdlet          Execute-RedisPipeline                              RespClient
    Cmdlet          Get-RedisConfig                                    RespClient
    Cmdlet          Get-RedisCurrentInfo                               RespClient
    Cmdlet          Get-RedisInfo                                      RespClient
    Cmdlet          Send-RedisCommand                                  RespClient
   Cmdlet          Send-RedisPipelineCommand                          RespClient

Thanks
Best regards
jgran

**Comment by guitarrapc** [comment]
Sorry for late response.

Alright, added it.
> nuget install RespClient

https://github.com/neuecc/RespClient/wiki/Install-RespClient

> Would you consider package for Chocolatey?

Not currently. Because RespClient is C# Class and PowerShell Module, while chocolatey main use case is package manager. I'm considering provide with  PowerShellGet but they are ClosedBeta and not reference whole Nuget currently.

**Comment by jgranduel** [comment]
Thank you very much.
