### ISSUE TITLE
Quotes support: ERR Protocol error: unbalanced quotes in request

### ISSUE THREAD

**Issue by jgranduel** [neuecc/RespClient#20]
Hi, 

Strings and multilines strings with quotes (apostrophe) are very common. What's the best way to persist them?

PS4> Send-RedisCommand "set today `"it's raining`""
OK
PS4> Send-RedisCommand "get today"
it's raining

# But shouldn't this command work?
PS4> Send-RedisCommand "set today 'it`'s raining'"
ERR Protocol error: unbalanced quotes in request

# Sometimes it closes Redis connection
Send-RedisCommand "set today 'it`'s raining'" 
ERR Protocol error: unbalanced quotes in request

or it closes the command (Sorry in French! kinda : "remote connection closed by remote host")
PS4 > Send-RedisCommand "set today 'it`'s raining'"
Send-RedisCommand : Une connexion existante a dû être fermée par l’hôte distant
Au caractère Ligne:1 : 1
+ Send-RedisCommand "set today 'it`'s raining'"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Send-RedisCommand], SocketException
    + FullyQualifiedErrorId : System.Net.Sockets.SocketException,Redis.PowerShell.Cmdlet.SendCommand

Multilines might also be handy.

#349 PS4> $m = @"
>>> hello
>>> bonjour
>>> sayonara
>>> "@
#350 PS4> Send-RedisCommand "set m `"$m`""
Send-RedisCommand : Une connexion existante a dû être fermée par l’hôte distant
Au caractère Ligne:1 : 1
+ Send-RedisCommand "set m `"$m`""
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Send-RedisCommand], SocketException
    + FullyQualifiedErrorId : System.Net.Sockets.SocketException,Redis.PowerShell.Cmdlet.SendCommand
    
Maybe converting to JSON with ConvertTo-Json ? Should the resulting JSON string always be single quoted?

PS4> $mAsJson = ConvertTo-Json $m
PS4> $mAsJson
"hello\nbonjour\nsayonara"
PS4> Send-RedisCommand "set m $mAsJson"
Send-RedisCommand : Une connexion existante a dû être fermée par l’hôte distant
Au caractère Ligne:1 : 1
+ Send-RedisCommand "set m $mAsJson"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Send-RedisCommand], SocketException
    + FullyQualifiedErrorId : System.Net.Sockets.SocketException,Redis.PowerShell.Cmdlet.SendCommand

Sometimes it works?! 
PS4> $m = @"
>>> Sayonara
>>> bonjour
>>> hello
>>> it's sunny
>>> "@
PS4> $mAsJson = ConvertTo-Json $m
PS4 D:\temp\2015> $mAsJson
"Sayonara\nbonjour\nhello\nit\u0027s sunny"
#381 PS4 D:\temp\2015> Send-RedisCommand "set m $mAsJson"
OK
PS4 > Send-RedisCommand "get m"
Sayonara
bonjour
hello
itu0027s sunny
#383 PS4 D:\temp\2015> Send-RedisCommand "get m" | ConvertFrom-Json
ConvertFrom-Json : Primitive JSON non valide : Sayonara.
Au caractère Ligne:1 : 29
+ Send-RedisCommand "get m" | ConvertFrom-Json
+                             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

PS4 D:\temp\2015> Send-RedisCommand "set m '$mAsJson'"
OK
PS4 D:\temp\2015> Send-RedisCommand "get m" | ConvertFrom-Json
Sayonara
bonjour
hello
it's sunny

Hope all ths is not too confusing. It might just be good practice...
Best regards,

**Comment by guitarrapc** [comment]
Let me check it. I will review and call you back:)

**Comment by guitarrapc** [comment]
Single Quote Issue : reproduces
----

> Send-RedisCommand "set today 'it`'s raining'" 
> ERR Protocol error: unbalanced quotes in request.

Json Issue : reproduces
-----
```powershell
$m = @"

Sayonara
bonjour
hello
it's sunny
"@
$mAsJson = ConvertTo-Json $m
```

```powershell
$mAsJson
```

> "Sayonara\nbonjour\nhello\nit\u0027s sunny"

```powershell
Send-RedisCommand "set m $mAsJson"
```

> OK

```powershell
Send-RedisCommand "get m"
```

> Sayonara
> bonjour
> hello
> itu0027s sunny

```powershell
Send-RedisCommand "get m" | ConvertFrom-Json
```

> ConvertFrom-Json : Primitive JSON non valide : Sayonara.
> Au caractère Ligne:1 : 29
> 
> Send-RedisCommand "get m" | ConvertFrom-Json
> ~~~~~~~~~~~~~~~~
> CategoryInfo : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
> FullyQualifiedErrorId : > System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

Avoid ConvertFrom-Json string Quote issue : Reproduces
----

```powershell
Send-RedisCommand "set m '$mAsJson'"
```
> OK

```powershell
Send-RedisCommand "get m" | ConvertFrom-Json
```

> Sayonara
> bonjour
> hello
> it's sunny

**Comment by guitarrapc** [comment]
Thanks you for providing single quote issues.

I believe avoiding ```ConvertFrom-Json``` by adding SingleQuote is correct way. Because it isn't Redis issue but a PowerShell Cmdlet issue.

If you want to pass ConvertFrom-Json without set json string without single quote, you can avoid with following awful code:(

```powershell
$m = @"

Sayonara
bonjour
hello
it's sunny
"@
Send-RedisCommand "set m $mAsJson"
$a = Send-RedisCommand "get m"
$a -split "\n" -join "\n" -replace "u0027", "\u0027" | %{"`"$_`""} | ConvertFrom-Json
```

**Comment by guitarrapc** [comment]
Now the issue is this.

```powershell
Send-RedisCommand "set today 'it`'s raining'" 
```

Let me check a while.

**Comment by guitarrapc** [comment]
So the issue is 

> Strings and multilines strings with quotes (apostrophe) are very common. What's the best way to persist them?

right?

Following is how Redis-Cli react with set quote issue.

![image](https://cloud.githubusercontent.com/assets/3856350/6981579/fae1a966-da3e-11e4-8bd0-d594149cb1e6.png)

It same to PowerShell.

![image](https://cloud.githubusercontent.com/assets/3856350/6981582/18477e04-da3f-11e4-883f-765ad64db46f.png)

 You have 2 options.

- Escape Quote inside set string

I don't think it's good because I don't want to touch inside WHAT I WANT TO SET.

```powershell
Send-RedisCommand "set today 'it\`'s raining'"
```

- Always quote set string with `"`"

I thinks it's prefer for every one.

```powershell
Send-RedisCommand "set today `"it's raining`""
```

**Comment by jgranduel** [comment]
Thank you very much for clear explanations.

**Comment by guitarrapc** [comment]
thx. Onething, about Sometimes it closes Redis connection.

This caused whenever next transaction of similar to ```ERR Protocol error: unbalanced quotes in request``` error was happen. This occur with Redis server suspect RespClient as broken and terminated by server-side.

I will check more detail but just for your information.
